Algoritmo "Concatenação"
// Descrição   : Concatenação
// Autor(a)    : João Vitor L. Coimbra
// Data atual  : 06/06/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o seu nome: ")
   leia(nome)
   escreval("Digite a sua idade: ")
   leia(numero)
   
   escreval(nome, " tem ", numero, " anos.")

Fimalgoritmo